# In this file you can add the plugins you want from github
# using the following syntax:

#[[plugins]]
#repo = 'author/repo'
#on_ft = ['ft1','ft2']
#build = 'method'
#if = 'condition'

# more info in the dein-toml

# example

#[[plugins]]
#repo = 'salsifis/vim-transpose'

# Colorschem used for true colors in the gallery
#[[plugins]]
#repo = 'tyrannicaltoucan/vim-quantum'

# Better Completer
[[plugins]]
repo = 'Shougo/deoplete.nvim'
# C / C++ / Obj-C
[[plugins]]
repo = 'zchee/deoplete-clang'

[[plugins]]
repo = 'Rip-Rip/clang_complete'


# Python
[[plugins]]
repo = 'zchee/deoplete-jedi'

# ZSH
[[plugins]]
repo = 'zchee/deoplete-zsh'

